// <auto-generated />
using System;
using GuoYunGlobal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuoYunGlobal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724110748_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("projectId");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("sources");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandVoice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("brandVoice");

                    b.Property<int?>("EstablishedYear")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("establishedYear");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("history");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("origin");

                    b.Property<string>("ProhibitedClaims")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("prohibitedClaims");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("projectId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.GeneratedAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("audience");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("channel");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("contentType");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("imageUrl");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("projectId");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("status");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("style");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("GeneratedAssets");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.MarketCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("country");

                    b.Property<string>("DimensionScores")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("dimensionScores");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("evidence");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("isSelected");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("projectId");

                    b.Property<string>("Risks")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("risks");

                    b.Property<int>("TotalScore")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("totalScore");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("MarketCandidates");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("brandId");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("category");

                    b.Property<decimal?>("DomesticPrice")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("domesticPrice");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("imageUrl");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("ingredients");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Process")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("process");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("sku");

                    b.Property<string>("Specs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("specs");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.Strategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channels")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("channels");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("Packaging")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("packaging");

                    b.Property<string>("Positioning")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("positioning");

                    b.Property<string>("Pricing")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("pricing");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("projectId");

                    b.Property<string>("Roadmap")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("roadmap");

                    b.Property<string>("SkuPlan")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("skuPlan");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.UploadedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("fileName");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("filePath");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("fileType");

                    b.Property<string>("ParsedContent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("parsedContent");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("projectId");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("uploadedAt");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("UploadedDocuments");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.AnalysisResult", b =>
                {
                    b.HasOne("GuoYunGlobal.Models.Entities.Project", "Project")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.Brand", b =>
                {
                    b.HasOne("GuoYunGlobal.Models.Entities.Project", "Project")
                        .WithOne("Brand")
                        .HasForeignKey("GuoYunGlobal.Models.Entities.Brand", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.GeneratedAsset", b =>
                {
                    b.HasOne("GuoYunGlobal.Models.Entities.Project", "Project")
                        .WithMany("GeneratedAssets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.MarketCandidate", b =>
                {
                    b.HasOne("GuoYunGlobal.Models.Entities.Project", "Project")
                        .WithMany("MarketCandidates")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.Product", b =>
                {
                    b.HasOne("GuoYunGlobal.Models.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuoYunGlobal.Models.Entities.Project", null)
                        .WithMany("Products")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.Strategy", b =>
                {
                    b.HasOne("GuoYunGlobal.Models.Entities.Project", "Project")
                        .WithOne("Strategy")
                        .HasForeignKey("GuoYunGlobal.Models.Entities.Strategy", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.UploadedDocument", b =>
                {
                    b.HasOne("GuoYunGlobal.Models.Entities.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GuoYunGlobal.Models.Entities.Project", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("Brand");

                    b.Navigation("Documents");

                    b.Navigation("GeneratedAssets");

                    b.Navigation("MarketCandidates");

                    b.Navigation("Products");

                    b.Navigation("Strategy");
                });
#pragma warning restore 612, 618
        }
    }
}
